/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Swing;
//      ItemID | ItemDescription | Price                                        PRODUCT
//      TaxID | TaxPercentage | CountryName                                     TAX
//      SaleID | NoItems | NoQty | TotalAmount | PaymentMethod | data time      SALE

import Domain.Payments.MyAdapter;
import Domain.Sales.*;
import Domain.Taxes.LebanonTax;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author boud-
 */
public class processSaleJFrame extends javax.swing.JFrame {
    
    private Product currentProduct = null;
    private Product yourProd = null;
    private final DefaultListModel<String> AvailableProductModel = new DefaultListModel();
    private List<Product> AvailableProductList = new ArrayList();
    private final List<Product> YourProductList = new ArrayList();
    private final DefaultListModel<String> YourItemsModel = new DefaultListModel();
    private int noItems = 0;
    private final List<Integer> noQtyList = new ArrayList();
    private double taxPercentage;
    private String arrayItem[];
    private double totalPrice = 0;
    private final Register register;
    
    /**
     * Creates new form GUI
     * @param reg
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public processSaleJFrame(Register reg) throws SQLException, ClassNotFoundException {
        this.register = new Register(new Catalog());
        initComponents();
        this.setTitle("POS" + " - " + Register.getCountry());
        this.jTabbedPane2.setVisible(false);
        AddItem.setEnabled(false);
        RemoveItem.setEnabled(false);
        ProdQty.setEnabled(false);
        Pay.setEnabled(false);
        EndSale.setEnabled(false);
        
        fillListProdFromCatalog();
        
        // displaying the price of each product selected
        jListAvailableProduct.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            ListRowSelectedPerformed(e);
        });
        
        jListYourItems.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if(e.getValueIsAdjusting()) {
                YourItemsListSelectedPerformed(e);
            }
        });
       
    }

    private void fillListProdFromCatalog(){
        // filling the list of products from the catalog 
        AvailableProductList = register.loadCatalog().getDescriptions();
        for (Product prod : AvailableProductList) {
            AvailableProductModel.addElement(prod.getDescription());
        }
        jListAvailableProduct.setModel(AvailableProductModel);
        
    }
    
    private void ListRowSelectedPerformed(ListSelectionEvent e) {
        AddItem.setEnabled(true);
        ProdQty.setEnabled(true);
        
        String itemString = AvailableProductModel.get(jListAvailableProduct.getSelectedIndex());
        currentProduct = register.getTransferFromDB().findByLikeProduct(itemString);
        Price.setText(currentProduct.getPrice() + " $");
    }
    
    private void YourItemsListSelectedPerformed(ListSelectionEvent e) {
        
        RemoveItem.setEnabled(true);
        
        String itemString = YourItemsModel.get(jListYourItems.getSelectedIndex());
        arrayItem = itemString.split(" ");
        yourProd = register.getTransferFromDB().findByLikeProduct(arrayItem[0]);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MakeNewSale2 = new java.awt.Button();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAvailableProduct = new javax.swing.JList<>();
        Price = new javax.swing.JTextField();
        AddItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListYourItems = new javax.swing.JList<>();
        EndSale = new javax.swing.JButton();
        NoItems = new javax.swing.JTextField();
        NoQty = new javax.swing.JTextField();
        RemoveItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ProdQty = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        TotalTax = new javax.swing.JTextField();
        TotalAmount = new javax.swing.JTextField();
        TotalPrice = new javax.swing.JTextField();
        Pay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS");

        MakeNewSale2.setActionCommand("MakeNewSale");
        MakeNewSale2.setLabel("MakeNewSale");
        MakeNewSale2.setName(""); // NOI18N
        MakeNewSale2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeNewSale2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MakeNewSale2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MakeNewSale2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jListAvailableProduct.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Items"));
        jListAvailableProduct.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListAvailableProduct);

        Price.setEditable(false);
        Price.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Price.setForeground(new java.awt.Color(0, 204, 51));
        Price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price.setText("PRICE");
        Price.setToolTipText("");
        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });

        AddItem.setText("AddItem");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });

        jListYourItems.setBorder(javax.swing.BorderFactory.createTitledBorder("Yours"));
        jScrollPane2.setViewportView(jListYourItems);

        EndSale.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        EndSale.setForeground(new java.awt.Color(153, 0, 0));
        EndSale.setText("END SALE");
        EndSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndSaleActionPerformed(evt);
            }
        });

        NoItems.setEditable(false);
        NoItems.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        NoItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoItems.setText("NoItems");
        NoItems.setToolTipText("");
        NoItems.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "NO.ITEMS"));

        NoQty.setEditable(false);
        NoQty.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        NoQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoQty.setText("NoQty");
        NoQty.setToolTipText("");
        NoQty.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "NO.QTY."));

        RemoveItem.setText("RemoveItem");
        RemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveItemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("QTY.");

        ProdQty.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NoItems, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NoQty, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddItem)
                    .addComponent(EndSale)
                    .addComponent(RemoveItem)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProdQty, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(12, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ProdQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddItem)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveItem))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(EndSale, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Store", jPanel2);

        TotalTax.setEditable(false);
        TotalTax.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        TotalTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalTax.setText("TotalTax");
        TotalTax.setToolTipText("");
        TotalTax.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "TOT.TAX"));

        TotalAmount.setEditable(false);
        TotalAmount.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        TotalAmount.setForeground(new java.awt.Color(153, 0, 0));
        TotalAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalAmount.setText("TotalAmount");
        TotalAmount.setToolTipText("");
        TotalAmount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 5), "TOT.AMOUNT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N
        TotalAmount.setCaretColor(new java.awt.Color(153, 0, 0));

        TotalPrice.setEditable(false);
        TotalPrice.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        TotalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalPrice.setText("TotalPrice");
        TotalPrice.setToolTipText("");
        TotalPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "TOT.PRICE"));

        Pay.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        Pay.setForeground(new java.awt.Color(153, 0, 0));
        Pay.setText("PAY");
        Pay.setToolTipText("");
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(Pay))
                            .addComponent(TotalTax, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Payment", jPanel3);

        jDesktopPane1.setLayer(jTabbedPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2)
                .addGap(128, 128, 128))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MakeNewSale2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeNewSale2ActionPerformed
        this.jTabbedPane2.setVisible(true);
    }//GEN-LAST:event_MakeNewSale2ActionPerformed

    private void EndSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndSaleActionPerformed
        // getting the tax percent from LebanonTax class
        taxPercentage = LebanonTax.INSTANCE.TaxPercentage(register);
        
        TotalPrice.setText(totalPrice + " $");
        TotalTax.setText(taxPercentage*100 + " %");
        TotalAmount.setText(totalPrice + totalPrice * taxPercentage + " $");
        
        Pay.setEnabled(true);
        this.jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_EndSaleActionPerformed

    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
        MyAdapter adap=null;
        String[] Payment = {"Cash", "CreditCard", "Check"};
        int optionChoosed = JOptionPane.showOptionDialog(null, "Choose your payment method !", "PAYMENT METHOD",
                0, JOptionPane.WARNING_MESSAGE, null, Payment, Payment[1]);
        
        String pay = register.makePayment(adap, Payment, optionChoosed);
        JOptionPane.showMessageDialog(null, pay);
        
        try {
        // save data to the db
        int totalQty = 0;
        for(int i = 0; i < noQtyList.size(); i++)
            totalQty += noQtyList.get(i);
        double totalAmount = totalPrice+ totalPrice*taxPercentage;
        Sale sale = register.makeNewSale(noItems,totalQty, totalAmount, Payment, optionChoosed);
        
        register.getPersistentStorage().createSale(sale);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        // CLEARING AND RESETTING ALL
        
        // buttons
        Pay.setEnabled(false);
        RemoveItem.setEnabled(false);
        EndSale.setEnabled(false);
        AddItem.setEnabled(false);
        
        // global vars
        noItems = 0;
        noQtyList.clear();
        totalPrice = 0;
        
        // text fields and labels
        NoItems.setText("NoItems");
        NoQty.setText("NoQty");
        ProdQty.setText(0 + "");
        Price.setText("Price");
        TotalPrice.setText("TotalPrice");
        TotalTax.setText("TotalTax");
        TotalAmount.setText("TotalAmount");
        
        // jLists and arrayLists
        YourItemsModel.clear();
        jListYourItems.setModel(YourItemsModel);
        YourProductList.clear();
        
        // tabbed panes
        this.jTabbedPane2.setSelectedIndex(0);
        this.jTabbedPane2.setVisible(false);
    }//GEN-LAST:event_PayActionPerformed

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed

        // filling the customer bag
        double prodPrice = currentProduct.getPrice();
        int prodQty = Integer.parseInt(ProdQty.getText());
        if (prodQty > 0) {
            EndSale.setEnabled(true);
            RemoveItem.setEnabled(true);
            YourItemsModel.addElement(currentProduct.getDescription()
                    + " (" + ProdQty.getText() + ")  -  "
                    + prodPrice * prodQty + " $");
            jListYourItems.setModel(YourItemsModel);
            totalPrice += prodPrice * prodQty;
            
            YourProductList.add(currentProduct);
        }
        
        // set the number of items
        noItems++;
        NoItems.setText(String.valueOf(noItems));
        
        // set the number of Quantity
        noQtyList.add(Integer.parseInt(ProdQty.getText()));
        int totalQty = 0;
        for(int i = 0; i < noQtyList.size(); i++)
            totalQty += noQtyList.get(i);
        NoQty.setText(totalQty + "");
    }//GEN-LAST:event_AddItemActionPerformed

    private void RemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveItemActionPerformed
        // In case the customer doesn't want the item anymore
        
        // updating total price
        String itemString = YourItemsModel.get(jListYourItems.getSelectedIndex());
        String[] array = itemString.split(" ");
//        System.out.println(array[5]);
        totalPrice -= Double.valueOf(array[5]);

        // updating number of items
        noItems--;
        NoItems.setText(String.valueOf(noItems));
        
        // updating number of quantity
        noQtyList.remove(jListYourItems.getSelectedIndex());
        int totalQty = 0;
        for(int i = 0; i < noQtyList.size(); i++)
            totalQty += noQtyList.get(i);
        NoQty.setText(totalQty + "");
        
        // removing selected item from jList and arrayList of products
        YourItemsModel.remove(jListYourItems.getSelectedIndex());
        jListYourItems.setModel(YourItemsModel);
        YourProductList.remove(yourProd);

        // disable button if list is empty
        if (YourItemsModel.isEmpty()) {
            RemoveItem.setEnabled(false);
            EndSale.setEnabled(false);
        }
    }//GEN-LAST:event_RemoveItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(processSaleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new processSaleJFrame(register).setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(processSaleJFrame.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(processSaleJFrame.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new processSaleJFrame(register).setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(processSaleJFrame.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(processSaleJFrame.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItem;
    private javax.swing.JButton EndSale;
    private java.awt.Button MakeNewSale2;
    private javax.swing.JTextField NoItems;
    private javax.swing.JTextField NoQty;
    private javax.swing.JButton Pay;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField ProdQty;
    private javax.swing.JButton RemoveItem;
    private javax.swing.JTextField TotalAmount;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JTextField TotalTax;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListAvailableProduct;
    private javax.swing.JList<String> jListYourItems;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
